### ISSUE TITLE
Can only select one person for a mission.

### ISSUE THREAD

**Issue by Kyoj1n** [tannerkrewson/snakeout#4]
Sometimes when selecting people for a mission it only lets the person select 1 person. When they select another the first check mark disappears and moves to the newly selected person. It seems the buttons also sometimes do not work.

This problem seems to happen when playing on a phone browser.

**Comment by seaerchin** [comment]
this problem happens on chrome on a laptop!

**Comment by tannerkrewson** [comment]
hmm, thanks for the report. i'm not sure why this would happen. i'm fairly sure it would not be related to what device or browser you are using. i would love to fix this so any more details or a way to reproduce would be appreciated!

**Comment by Kyoj1n** [comment]
If I remember correctly it only seemed to occur after finishing one game and then using the option to start a new game with the same players.

**Comment by nishant-tiwari01** [comment]
I also faced this issue, yes I also observed this 
"it only seemed to occur after finishing one game and then using the option to start a new game with the same players."

**Comment by tannerkrewson** [comment]
Ok! This issue should be fixed now! Thanks for everyone's help!

Fixed in 183873fa64453d240debc5cf505c9c7fd7d7dbe2. I was able to reproduce the bug randomly, but I couldn't figure out how to force it to happen. 😢 Regardless, the bug didn't seem to happen with this fix! 🎉
